project:
  type: website
  output-dir: docs

website:
  title: "Soren Laney's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sorenlaney
      - icon: twitter
        href: https://twitter.com/Soren_Laney_
format:
  html:
    theme: cosmo
    css: styles.css



